% ##### COMPARE COMPONENTS REMOVED BETWEEN PIPELINES #####

% This script the total number of components removed and the variance
% explained by the components following the step 4 FastICA between the
% FastICA and SOUND pipelines.

% The script requires data generated by the code in:
% pipeline_step4.m

% Author: Nigel Rogasch, University of Adelaide, 2021

clear; close all; clc;

% Participant IDs
ID = {'121','123','126','127','129','137','138','139','142','143','145','146','147','148'};

% Conditions
condition = {'FastICA','SOUND'};

saveName = 'model_comparison';

% Step No
stepNo = 'step4';

% Data path
pathIn = '/projects/kg98/Mana/decay/highIntensity_separateBlocks_withTMSPulse/';

% EEGLAB
addpath(genpath('/projects/kg98/Mana/Scripts/Toolboxes/eeglab14_1_2b/'));
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab; close;

% Fieldtrip
addpath('/projects/kg98/Mana/Scripts/Toolboxes/fieldtrip-20180619');
ft_defaults;

for cx = 1:length(condition)
    for idx = 1:length(ID)
        
        % Load the data
        if strcmp(stepNo,'step3') && strcmp(condition{cx},'FastICA')
            filename = [ID{idx},'_FEF_Decaytest_withTMSPulse_',stepNo,'_','FastICA_clean','.set'];
        else
            filename = [ID{idx},'_FEF_Decaytest_withTMSPulse_',stepNo,'_',condition{cx},'.set'];
        end
        
        EEG = pop_loadset('filename',filename,'filepath',pathIn);
        
        if strcmp(condition{cx},'FastICA')
            components.(condition{cx}).number(idx) = sum(EEG.icaCompClass.TESA2.compClass~=1);
            components.(condition{cx}).percent(idx) = sum(EEG.icaCompClass.TESA2.compClass~=1)./length(EEG.icaCompClass.TESA2.compClass);
            components.(condition{cx}).variance(idx) = sum(EEG.icaCompClass.TESA2.compVars(EEG.icaCompClass.TESA2.compClass~=1));
        elseif strcmp(condition{cx},'SOUND')
            components.(condition{cx}).number(idx) = sum(EEG.icaCompClass.TESA1.compClass~=1);
            components.(condition{cx}).percent(idx) = sum(EEG.icaCompClass.TESA1.compClass~=1)./length(EEG.icaCompClass.TESA1.compClass);
            components.(condition{cx}).variance(idx) = sum(EEG.icaCompClass.TESA1.compVars(EEG.icaCompClass.TESA1.compClass~=1));
        end
        
        
    end
end

%%
% Compare number of components
[~,pn] = ttest(components.FastICA.number,components.SOUND.number);

% Compare variance removed
[~,pv] = ttest(components.FastICA.variance,components.SOUND.variance);

meanFI = mean(components.FastICA.variance);
meanS = mean(components.SOUND.variance);
sdFI = std(components.FastICA.variance,[]);
sdS = std(components.SOUND.variance,[]);

% save([pathIn,saveName,'_',stepNo,'.mat'],'tep','gmfa','ID','condition');