% ##### CALCULATE TRIALS AND CHANNELS REMOVED BETWEEN PIPELINES #####

% This script calculates the mean number of channels and trials manually
% removed in step 2 of the pipeline.

% The script requires data generated by the code in:
% pipeline_step4.m

% Author: Nigel Rogasch, University of Adelaide, 2021

% Participant IDs
ID = {'121','123','126','127','129','137','138','139','142','143','145','146','147','148'};

% Select condition to clean
condition = {'FastICA'};

% Data path
pathIn = '/projects/kg98/Mana/decay/highIntensity_separateBlocks_withTMSPulse/';

% EEGLAB
addpath(genpath('/projects/kg98/Mana/Scripts/Toolboxes/eeglab14_1_2b/'));
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab; close;

for cx = 1:length(condition)
    for idx = 1:length(ID)
        
        % Load the data
        filename = [ID{idx},'_FEF_Decaytest_withTMSPulse_step4_',condition{cx},'.set'];
        EEG = pop_loadset('filename',filename,'filepath',pathIn);
        
        % Trials
        trials(idx) = 120-size(EEG.data,3);
        
        % Electrodes
        electrodes(idx) = length(EEG.badchannels);
        
    end
end

meanT = mean(trials);
stdT = std(trials);
minT = min(trials);
maxT = max(trials);

meanE = mean(electrodes);
stdE = std(electrodes);
minE = min(electrodes);
maxE = max(electrodes);
